# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72bb5fad9481b8364e21f1c59346df2a33c67da7669a0cc4fb100c9ca7d182b1b3e2baf243af54f713b0b1adf004764485ee58335ab9f7ef5fdf1fe3456ffc76

test:
  secret_key_base: eb782a68d66111492aef4368515f66980538f62c50c78a42e8ba4d6f364c17a98a33719855595f53deffb256cd3ce610010da9e5bd36ce916dada6731897f15b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
